"""init schema

Revision ID: 217a8df9619f
Revises: 
Create Date: 2026-05-02 01:10:26.938420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217a8df9619f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCRAPING', 'COMPLETED', 'FAILED', name='crawlstatus'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('completed_pages', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crawl_session_created', 'crawl_session', ['created_at'], unique=False)
    op.create_index('idx_crawl_session_status', 'crawl_session', ['status'], unique=False)
    op.create_table('daily_analytic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_chats', sa.Integer(), nullable=True),
    sa.Column('new_leads', sa.Integer(), nullable=True),
    sa.Column('fallbacks', sa.Integer(), nullable=True),
    sa.Column('top_intents', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('major',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('degree_type', sa.String(), nullable=True),
    sa.Column('major_type', sa.Enum('UNDERGRAD_MAJOR', 'GRAD_MAJOR', 'CERTIFICATE_PROGRAM', name='majortype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ocr_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rq_job_id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('source_file_hash', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('pipeline_version', sa.String(), nullable=True),
    sa.Column('source_r2_key', sa.String(), nullable=True),
    sa.Column('md_r2_key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version_start', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('suggested_category', sa.JSON(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_to_kb', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_job_content_hash'), 'ocr_job', ['content_hash'], unique=False)
    op.create_index(op.f('ix_ocr_job_pipeline_version'), 'ocr_job', ['pipeline_version'], unique=False)
    op.create_index(op.f('ix_ocr_job_rq_job_id'), 'ocr_job', ['rq_job_id'], unique=True)
    op.create_index(op.f('ix_ocr_job_source_file_hash'), 'ocr_job', ['source_file_hash'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'COUNSELOR', name='staffrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('crawl_page_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crawl_session_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('detected_title', sa.String(), nullable=True),
    sa.Column('page_index', sa.Integer(), nullable=True),
    sa.Column('md_r2_key', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('suggested_metadata', sa.JSON(), nullable=True),
    sa.Column('firecrawl_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('version_start', sa.Integer(), nullable=True),
    sa.Column('sent_to_kb', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crawl_session_id'], ['crawl_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_session_id', 'source_url', name='uq_crawl_page_job_session_source_url')
    )
    op.create_index('idx_crawl_page_job_created', 'crawl_page_job', ['created_at'], unique=False)
    op.create_index('idx_crawl_page_job_sent_to_kb', 'crawl_page_job', ['sent_to_kb'], unique=False)
    op.create_index('idx_crawl_page_job_session', 'crawl_page_job', ['crawl_session_id'], unique=False)
    op.create_index('idx_crawl_page_job_status', 'crawl_page_job', ['status'], unique=False)
    op.create_index(op.f('ix_crawl_page_job_content_hash'), 'crawl_page_job', ['content_hash'], unique=False)
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('TUITION', 'SCHOLARSHIP', 'REQUIREMENT', 'DEADLINE', 'PROCESS', 'MAJOR_INFO', 'FAQ', name='admissioncategory'), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('needs_embedding', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_category', 'knowledge_chunk', ['category'], unique=False)
    op.create_index('idx_knowledge_is_active', 'knowledge_chunk', ['is_active'], unique=False)
    op.create_index('idx_knowledge_major_id', 'knowledge_chunk', ['major_id'], unique=False)
    op.create_index('idx_knowledge_year', 'knowledge_chunk', ['year'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('high_school', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'APPLIED', 'ENROLLED', 'LOST', name='leadstatus'), nullable=True),
    sa.Column('temperature', sa.Enum('HOT', 'WARM', 'COLD', name='leadtemperature'), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('ielts', sa.Float(), nullable=True),
    sa.Column('sat', sa.Integer(), nullable=True),
    sa.Column('act', sa.Integer(), nullable=True),
    sa.Column('cv_url', sa.String(), nullable=True),
    sa.Column('essay_url', sa.String(), nullable=True),
    sa.Column('transcript_url', sa.String(), nullable=True),
    sa.Column('extracurriculars', sa.JSON(), nullable=True),
    sa.Column('ability_score', sa.Float(), nullable=True),
    sa.Column('aspiration_score', sa.Float(), nullable=True),
    sa.Column('creativity_score', sa.Float(), nullable=True),
    sa.Column('commitment_score', sa.Float(), nullable=True),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('assigned_staff_id', sa.UUID(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index('idx_lead_gpa', 'lead', ['gpa'], unique=False)
    op.create_index('idx_lead_ielts', 'lead', ['ielts'], unique=False)
    op.create_index('idx_lead_last_interaction_at', 'lead', ['last_interaction_at'], unique=False)
    op.create_index('idx_lead_score', 'lead', ['score'], unique=False)
    op.create_index('idx_lead_temperature', 'lead', ['temperature'], unique=False)
    op.create_table('scholarship_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MERIT', 'NEED_BASED', 'TALENT', 'EARLY_BIRD', 'SUPPLEMENTARY', name='scholarshiptype'), nullable=False),
    sa.Column('scope', sa.Enum('GLOBAL', 'MAJOR_PRIORITY', 'PROFILE_BASED', name='scholarshipscope'), nullable=False),
    sa.Column('value_type', sa.Enum('PERCENT', 'AMOUNT', 'FULL', name='scholarshipvaluetype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scholarship_is_active', 'scholarship_policy', ['is_active'], unique=False)
    op.create_index('idx_scholarship_major_id', 'scholarship_policy', ['major_id'], unique=False)
    op.create_index('idx_scholarship_scope', 'scholarship_policy', ['scope'], unique=False)
    op.create_index('idx_scholarship_type', 'scholarship_policy', ['type'], unique=False)
    op.create_index('idx_scholarship_year', 'scholarship_policy', ['year'], unique=False)
    op.create_table('tuition_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('fee_type', sa.Enum('CREDIT', 'SEMESTER', 'YEAR', 'HYBRID', name='feetype'), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('major_id', 'year', 'fee_type', name='uq_major_year_fee_type')
    )
    op.create_index('idx_tuition_is_active', 'tuition_policy', ['is_active'], unique=False)
    op.create_index('idx_tuition_major_id', 'tuition_policy', ['major_id'], unique=False)
    op.create_index('idx_tuition_year', 'tuition_policy', ['year'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('NEW', 'PROFILE_SUBMITTED', 'DOCUMENT_REVIEW', 'INTERVIEW', 'OFFER_EXTENDED', 'ENROLLED', 'REJECTED', name='admissionstage'), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(), nullable=True),
    sa.Column('source_channel', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_application_admission_year', 'application', ['admission_year'], unique=False)
    op.create_index('idx_application_lead_id', 'application', ['lead_id'], unique=False)
    op.create_index('idx_application_major_id', 'application', ['major_id'], unique=False)
    op.create_index('idx_application_stage', 'application', ['stage'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('WEB', 'ZALO', 'FACEBOOK', 'TELEGRAM', name='channel'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'HANDOFF', 'CLOSED', name='conversationstatus'), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_created_at', 'conversation', ['created_at'], unique=False)
    op.create_index('idx_conversation_lead_id', 'conversation', ['lead_id'], unique=False)
    op.create_index('idx_conversation_status', 'conversation', ['status'], unique=False)
    op.create_table('lead_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('score_delta', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_major_interest',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('major_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['major_id'], ['major.id'], ),
    sa.PrimaryKeyConstraint('lead_id', 'major_id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_conversation_id', 'message', ['conversation_id'], unique=False)
    op.create_index('idx_message_created_at', 'message', ['created_at'], unique=False)
    op.create_index('idx_message_intent', 'message', ['intent'], unique=False)
    op.create_index('idx_message_is_fallback', 'message', ['is_fallback'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('HOT_LEAD', 'FOLLOW_UP', 'DEADLINE', 'APPLICATION_UPDATE', 'TUITION_INFO', 'FAQ_MISSING', name='notificationtype'), nullable=False),
    sa.Column('target', sa.Enum('ADMIN', 'STAFF', 'USER', name='notificationtarget'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_conversation_id', 'notification', ['conversation_id'], unique=False)
    op.create_index('idx_notification_created_at', 'notification', ['created_at'], unique=False)
    op.create_index('idx_notification_lead_id', 'notification', ['lead_id'], unique=False)
    op.create_index('idx_notification_staff_id', 'notification', ['staff_id'], unique=False)
    op.create_index('idx_notification_status', 'notification', ['status'], unique=False)
    op.create_index('idx_notification_target', 'notification', ['target'], unique=False)
    op.create_index('idx_notification_type', 'notification', ['type'], unique=False)
    op.create_table('faq_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('normalized', sa.String(), nullable=False),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=True),
    sa.Column('last_conversation_id', sa.UUID(), nullable=True),
    sa.Column('last_user_message_id', sa.UUID(), nullable=True),
    sa.Column('last_assistant_message_id', sa.UUID(), nullable=True),
    sa.Column('last_asked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['last_assistant_message_id'], ['message.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_conversation_id'], ['conversation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_user_message_id'], ['message.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized')
    )
    op.create_index('idx_faq_count', 'faq_analytics', ['count'], unique=False)
    op.create_index('idx_faq_intent', 'faq_analytics', ['intent'], unique=False)
    op.create_index('idx_faq_last_asked_at', 'faq_analytics', ['last_asked_at'], unique=False)
    op.create_index('idx_faq_last_assistant_message_id', 'faq_analytics', ['last_assistant_message_id'], unique=False)
    op.create_index('idx_faq_last_conversation_id', 'faq_analytics', ['last_conversation_id'], unique=False)
    op.create_index('idx_faq_last_user_message_id', 'faq_analytics', ['last_user_message_id'], unique=False)
    op.create_table('message_chunk_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunk.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_msg_chunk_chunk_id', 'message_chunk_usage', ['chunk_id'], unique=False)
    op.create_index('idx_msg_chunk_created_at', 'message_chunk_usage', ['created_at'], unique=False)
    op.create_index('idx_msg_chunk_message_id', 'message_chunk_usage', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_msg_chunk_message_id', table_name='message_chunk_usage')
    op.drop_index('idx_msg_chunk_created_at', table_name='message_chunk_usage')
    op.drop_index('idx_msg_chunk_chunk_id', table_name='message_chunk_usage')
    op.drop_table('message_chunk_usage')
    op.drop_index('idx_faq_last_user_message_id', table_name='faq_analytics')
    op.drop_index('idx_faq_last_conversation_id', table_name='faq_analytics')
    op.drop_index('idx_faq_last_assistant_message_id', table_name='faq_analytics')
    op.drop_index('idx_faq_last_asked_at', table_name='faq_analytics')
    op.drop_index('idx_faq_intent', table_name='faq_analytics')
    op.drop_index('idx_faq_count', table_name='faq_analytics')
    op.drop_table('faq_analytics')
    op.drop_index('idx_notification_type', table_name='notification')
    op.drop_index('idx_notification_target', table_name='notification')
    op.drop_index('idx_notification_status', table_name='notification')
    op.drop_index('idx_notification_staff_id', table_name='notification')
    op.drop_index('idx_notification_lead_id', table_name='notification')
    op.drop_index('idx_notification_created_at', table_name='notification')
    op.drop_index('idx_notification_conversation_id', table_name='notification')
    op.drop_table('notification')
    op.drop_index('idx_message_is_fallback', table_name='message')
    op.drop_index('idx_message_intent', table_name='message')
    op.drop_index('idx_message_created_at', table_name='message')
    op.drop_index('idx_message_conversation_id', table_name='message')
    op.drop_table('message')
    op.drop_table('lead_major_interest')
    op.drop_table('lead_activity')
    op.drop_index('idx_conversation_status', table_name='conversation')
    op.drop_index('idx_conversation_lead_id', table_name='conversation')
    op.drop_index('idx_conversation_created_at', table_name='conversation')
    op.drop_table('conversation')
    op.drop_index('idx_application_stage', table_name='application')
    op.drop_index('idx_application_major_id', table_name='application')
    op.drop_index('idx_application_lead_id', table_name='application')
    op.drop_index('idx_application_admission_year', table_name='application')
    op.drop_table('application')
    op.drop_index('idx_tuition_year', table_name='tuition_policy')
    op.drop_index('idx_tuition_major_id', table_name='tuition_policy')
    op.drop_index('idx_tuition_is_active', table_name='tuition_policy')
    op.drop_table('tuition_policy')
    op.drop_index('idx_scholarship_year', table_name='scholarship_policy')
    op.drop_index('idx_scholarship_type', table_name='scholarship_policy')
    op.drop_index('idx_scholarship_scope', table_name='scholarship_policy')
    op.drop_index('idx_scholarship_major_id', table_name='scholarship_policy')
    op.drop_index('idx_scholarship_is_active', table_name='scholarship_policy')
    op.drop_table('scholarship_policy')
    op.drop_index('idx_lead_temperature', table_name='lead')
    op.drop_index('idx_lead_score', table_name='lead')
    op.drop_index('idx_lead_last_interaction_at', table_name='lead')
    op.drop_index('idx_lead_ielts', table_name='lead')
    op.drop_index('idx_lead_gpa', table_name='lead')
    op.drop_table('lead')
    op.drop_index('idx_knowledge_year', table_name='knowledge_chunk')
    op.drop_index('idx_knowledge_major_id', table_name='knowledge_chunk')
    op.drop_index('idx_knowledge_is_active', table_name='knowledge_chunk')
    op.drop_index('idx_knowledge_category', table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_index(op.f('ix_crawl_page_job_content_hash'), table_name='crawl_page_job')
    op.drop_index('idx_crawl_page_job_status', table_name='crawl_page_job')
    op.drop_index('idx_crawl_page_job_session', table_name='crawl_page_job')
    op.drop_index('idx_crawl_page_job_sent_to_kb', table_name='crawl_page_job')
    op.drop_index('idx_crawl_page_job_created', table_name='crawl_page_job')
    op.drop_table('crawl_page_job')
    op.drop_table('staff')
    op.drop_index(op.f('ix_ocr_job_source_file_hash'), table_name='ocr_job')
    op.drop_index(op.f('ix_ocr_job_rq_job_id'), table_name='ocr_job')
    op.drop_index(op.f('ix_ocr_job_pipeline_version'), table_name='ocr_job')
    op.drop_index(op.f('ix_ocr_job_content_hash'), table_name='ocr_job')
    op.drop_table('ocr_job')
    op.drop_table('major')
    op.drop_table('daily_analytic')
    op.drop_index('idx_crawl_session_status', table_name='crawl_session')
    op.drop_index('idx_crawl_session_created', table_name='crawl_session')
    op.drop_table('crawl_session')
    # ### end Alembic commands ###
